export const COMMAND_TRANSPORT = 'src/shared/runtime/command.runtime.ts';

export const commandOwners = {
  'src/services/app-settings.service.ts': ['load_app_settings', 'save_app_settings'],
  'src/services/app-log.service.ts': ['append_app_log', 'get_app_log_status', 'open_app_log_file', 'clear_app_log_file'],
  'src/services/app-config.service.ts': ['open_config_dir', 'clear_config_files'],
  'src/services/workspace-state.service.ts': ['load_workspace', 'save_workspace'],
  'src/services/mod-creation.service.ts': ['create_mod'],
  'src/services/core-assets.service.ts': ['scan_core_fields', 'scan_core_graphics', 'invalidate_core_cache'],
  'src/services/directory.service.ts': ['detect_directory', 'scan_game_overview'],
  'src/services/project-session.service.ts': [
    'open_project_session',
    'close_project_session',
    'invalidate_project_session',
    'synchronize_committed_write',
  ],
  'src/services/window.service.ts': [
    'open_managed_window',
    'update_managed_window_status',
    'reserve_window_targets',
    'release_window_targets',
    'retarget_managed_window',
    'request_session_window_close',
    'cancel_window_close_request',
  ],
  'src/services/source-options.service.ts': ['query_csv_source_options'],
  'src/services/hull-reference.service.ts': ['query_hull_references'],
  'src/services/resource-cache.service.ts': ['query_resource_data_urls'],
  'src/services/resource-reference.service.ts': ['resolve_mod_relative_path'],
  'src/services/entity-query.service.ts': [
    'query_entity',
    'query_entity_edit_target',
    'query_entity_identity_intent',
    'query_entity_list',
    'query_editor_draft_resources',
  ],
  'src/shared/api/files-api.ts': ['load_editable_file', 'query_text_identity_intent', 'follow_text_identity'],
  'src/services/csv-table.service.ts': ['save_csv_patch', 'query_csv_table_window', 'query_csv_row_preview'],
  'src/services/files.service.ts': ['save_text_file', 'transcode_file_to_utf8', 'save_mod_files'],
  'src/services/editor.service.ts': ['load_imported_editor_spec_file', 'save_editor_spec'],
  'src/services/config-entity.service.ts': [
    'save_mod_info',
    'save_indexed_config_entity',
    'create_indexed_config_entity',
    'delete_indexed_config_entity',
    'save_variant_entity',
    'create_variant_entity',
    'delete_variant_entity',
    'save_skin_entity',
    'create_skin_entity',
    'delete_skin_entity',
  ],
  'src/services/file-history.service.ts': ['apply_file_change_set', 'query_file_history', 'clear_file_history'],
};
